import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '../utils/logger';
import { AIGeneratedTestCase } from '../types';
import { AzureWorkItem } from '../types';

/**
 * TestCaseWriter converts AI-generated test cases into Playwright TypeScript spec files
 * and saves them to the correct location in the framework directory structure.
 *
 * Output location: tests/crm/<sanitized-title>.spec.ts
 *                  tests/inventory/<sanitized-title>.spec.ts
 */
export class TestCaseWriter {
  private readonly logger = new Logger('TestCaseWriter');
  private readonly testsRootDir: string;

  constructor(testsRootDir = 'tests') {
    this.testsRootDir = path.resolve(process.cwd(), testsRootDir);
  }

  // ─── Public API ────────────────────────────────────────────────────────────

  /**
   * Write a complete spec file for all test cases generated from a single User Story.
   * Returns the absolute path of the written file.
   */
  async writeTestFile(
    story: AzureWorkItem,
    testCases: AIGeneratedTestCase[],
    appContext: 'CRM' | 'InventoryManagement' = 'CRM'
  ): Promise<string> {
    const subDir = appContext === 'CRM' ? 'crm' : 'inventory';
    const fileName = `${this.sanitizeFileName(story.title)}.spec.ts`;
    const outputDir = path.join(this.testsRootDir, subDir);
    const filePath = path.join(outputDir, fileName);

    this.ensureDirectory(outputDir);

    // If file already exists, back it up
    if (fs.existsSync(filePath)) {
      const backupPath = filePath.replace('.spec.ts', `.backup.${Date.now()}.spec.ts`);
      fs.renameSync(filePath, backupPath);
      this.logger.warn(`Existing spec backed up to: ${backupPath}`);
    }

    const content = this.buildSpecFileContent(story, testCases, appContext);
    fs.writeFileSync(filePath, content, 'utf-8');
    this.logger.info(`Spec file written: ${filePath}`);
    return filePath;
  }

  /**
   * Append a single test case to an existing spec file.
   */
  async appendTestCase(filePath: string, testCase: AIGeneratedTestCase): Promise<void> {
    if (!fs.existsSync(filePath)) {
      throw new Error(`Spec file not found: ${filePath}`);
    }

    const existing = fs.readFileSync(filePath, 'utf-8');

    // Insert before the closing '});' of the describe block
    const insertPoint = existing.lastIndexOf('});');
    if (insertPoint === -1) {
      throw new Error('Could not find closing describe block in spec file');
    }

    const newTestBlock = `\n${this.indentCode(testCase.playwrightCode, 2)}\n`;
    const updated =
      existing.substring(0, insertPoint) + newTestBlock + existing.substring(insertPoint);

    fs.writeFileSync(filePath, updated, 'utf-8');
    this.logger.info(`Appended test case "${testCase.title}" to ${filePath}`);
  }

  /**
   * Write a JSON manifest of generated test cases alongside the spec file.
   * Useful for tracking what was generated vs what was actually implemented.
   */
  async writeManifest(
    story: AzureWorkItem,
    testCases: AIGeneratedTestCase[],
    testCaseIds: number[],
    appContext: 'CRM' | 'InventoryManagement' = 'CRM'
  ): Promise<string> {
    const subDir = appContext === 'CRM' ? 'crm' : 'inventory';
    const fileName = `${this.sanitizeFileName(story.title)}.manifest.json`;
    const outputDir = path.join(this.testsRootDir, subDir);
    const filePath = path.join(outputDir, fileName);

    this.ensureDirectory(outputDir);

    const manifest = {
      workItemId: story.id,
      title: story.title,
      generatedAt: new Date().toISOString(),
      azureTestCaseIds: testCaseIds,
      testCases: testCases.map((tc, i) => ({
        azureTestCaseId: testCaseIds[i] ?? null,
        title: tc.title,
        priority: tc.priority,
        tags: tc.tags,
        stepsCount: tc.steps.length,
      })),
    };

    fs.writeFileSync(filePath, JSON.stringify(manifest, null, 2), 'utf-8');
    this.logger.info(`Manifest written: ${filePath}`);
    return filePath;
  }

  // ─── File Content Builder ──────────────────────────────────────────────────

  private buildSpecFileContent(
    story: AzureWorkItem,
    testCases: AIGeneratedTestCase[],
    appContext: 'CRM' | 'InventoryManagement'
  ): string {
    const storageStateFile =
      appContext === 'CRM' ? 'crm.storageState.json' : 'inventory.storageState.json';

    const tags = [...new Set(testCases.flatMap(tc => tc.tags))].join(', ');
    const describeName = `[US-${story.id}] ${story.title}`;

    const testBlocks = testCases.map(tc => this.buildTestBlock(tc, story.id)).join('\n\n');

    return `/**
 * AUTO-GENERATED BY AI TEST CASE GENERATOR
 * Azure DevOps Work Item: #${story.id}
 * Title: ${story.title}
 * Generated: ${new Date().toISOString()}
 * Tags: ${tags}
 *
 * DO NOT EDIT the test structure — update the user story and re-run:
 *   npm run sync:azure -- --id ${story.id}
 *
 * Description:
 * ${this.wordWrap(story.description, 80, ' * ')}
 */

import { test, expect } from '@playwright/test';
import { LoginPage } from '../../src/pages/LoginPage';
import { CRMDashboardPage } from '../../src/pages/CRMDashboardPage';
import { ContactsPage } from '../../src/pages/crm/ContactsPage';
import { AccountsPage } from '../../src/pages/crm/AccountsPage';
import { LeadsPage } from '../../src/pages/crm/LeadsPage';

test.describe('${describeName}', () => {
  // storageState is set at the project level in playwright.config.ts
  // Authentication is handled by tests/auth/auth.setup.ts

${testBlocks}
});
`;
  }

  private buildTestBlock(tc: AIGeneratedTestCase, workItemId: number): string {
    const tagAnnotations = tc.tags
      .map(tag => `  test.info().annotations.push({ type: 'tag', description: '${tag}' });`)
      .join('\n');

    // Use the AI-generated code if it looks complete, otherwise build a skeleton
    const codeBody = this.isCompleteTestCode(tc.playwrightCode)
      ? this.indentCode(this.extractTestBody(tc.playwrightCode), 2)
      : this.buildSkeletonTestBody(tc, workItemId);

    const priorityAnnotation = `  test.info().annotations.push({ type: 'priority', description: '${tc.priority}' });`;
    const azureAnnotation = `  test.info().annotations.push({ type: 'azureWorkItem', description: 'US-${workItemId}' });`;

    return `  /**
   * ${tc.title}
   * Priority: ${tc.priority}
   * Tags: ${tc.tags.join(', ')}
   *
   * Description: ${tc.description}
   *
   * Preconditions:
${tc.preconditions.map(p => `   *   - ${p}`).join('\n')}
   *
   * Expected Outcome: ${tc.expectedOutcome}
   */
  test('[US-${workItemId}] ${tc.title}', async ({ page }) => {
${azureAnnotation}
${priorityAnnotation}
${tagAnnotations}

${codeBody}
  });`;
  }

  private buildSkeletonTestBody(tc: AIGeneratedTestCase, workItemId: number): string {
    const lines: string[] = [];
    lines.push(`    // ── Page Object Setup ──────────────────────────────────────────`);
    lines.push(`    const dashboard = new CRMDashboardPage(page);`);
    lines.push(`    const contacts = new ContactsPage(page);`);
    lines.push(`    const accounts = new AccountsPage(page);`);
    lines.push(`    const leads = new LeadsPage(page);`);
    lines.push(``);

    tc.steps.forEach(step => {
      lines.push(`    // Step ${step.stepNumber}: ${step.action}`);
      if (step.locatorHint) {
        lines.push(`    // Locator hint: ${step.locatorHint}`);
      }
      lines.push(`    // TODO: implement`);
      lines.push(`    // Expected: ${step.expectedResult}`);
      lines.push(``);
    });

    lines.push(`    // ── Final Assertion ────────────────────────────────────────────`);
    lines.push(`    // ${tc.expectedOutcome}`);
    lines.push(`    // expect(await dashboard.getRecordTitle()).toContain('expected value');`);

    return lines.join('\n');
  }

  // ─── Helpers ───────────────────────────────────────────────────────────────

  private isCompleteTestCode(code: string): boolean {
    if (!code || code.trim().length < 50) return false;
    // Must have at least one expect() call to be considered complete
    return code.includes('expect(') || code.includes('await ');
  }

  /**
   * Extract the body of a test() block — strips the outer test() wrapper
   * since we add our own annotations.
   */
  private extractTestBody(code: string): string {
    // If the code is a full test() block, extract just the body
    const bodyMatch = code.match(/test\s*\([^)]+,\s*async\s*\(\s*\{[^}]*\}\s*\)\s*=>\s*\{([\s\S]*)\}\s*\)\s*;?\s*$/);
    if (bodyMatch) {
      return bodyMatch[1].trim();
    }
    // Otherwise return as-is (already just the body)
    return code.trim();
  }

  private indentCode(code: string, spaces: number): string {
    const indent = ' '.repeat(spaces);
    return code
      .split('\n')
      .map(line => (line.trim() === '' ? '' : `${indent}${line}`))
      .join('\n');
  }

  private sanitizeFileName(title: string): string {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .substring(0, 80);
  }

  private ensureDirectory(dirPath: string): void {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      this.logger.info(`Created directory: ${dirPath}`);
    }
  }

  private wordWrap(text: string, width: number, prefix = ''): string {
    if (!text) return '(no description)';
    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';
    for (const word of words) {
      if ((current + ' ' + word).length > width) {
        lines.push(current);
        current = word;
      } else {
        current = current ? `${current} ${word}` : word;
      }
    }
    if (current) lines.push(current);
    return lines.join(`\n${prefix}`);
  }
}
